# Generated by Django 2.2.16 on 2022-07-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220715_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_hex',
            field=models.CharField(default='d94c722648da4716d6ddf375b7031fc13406bbb32c6498fb9adaecd95842415c', max_length=256),
            preserve_default=False,
        ),
    ]
