# Generated by Django 2.2.16 on 2022-07-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_secret_hex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='secret_hex',
            new_name='confirmation_code',
        ),
    ]
